### PR TITLE
Add shortcode UI for protected embeds

### PR DESCRIPTION
**Pull request by goldenapples**
Adds a basic UI for editing height, width, and other attributes.
Includes some functionality for updating the embed code itself.

### CODE REVIEW

**Comment by goldenapples** [comment]
@joehoyle We've added this locally to provide a little bit of management tools for these embeds. Feel free to merge it on your end if you think it'd be useful.

**Comment by joehoyle** [comment]
Looks like this inadvertently reverts the addition of the object-cache stuff, I'll fix up!

**Comment by goldenapples** [comment]
I was wondering about that... I didn't have that commit locally, and it didn't look like it was working since I didn't see any `wp_cache_set` line in there. How does the row get added to the cache in the first place?

**Comment by joehoyle** [comment]
Oh good point :P possible oversight!

**Comment by joehoyle** [comment]
Closed in #7

**Pull request merged**
